---
pushgateway_version: 1.11.1
pushgateway_binary_url: "https://github.com/{{ _pushgateway_repo }}/releases/download/v{{ pushgateway_version }}/\
                         pushgateway-{{ pushgateway_version }}.{{ ansible_facts['system'] | lower }}-{{ _pushgateway_go_ansible_arch }}.tar.gz"
pushgateway_checksums_url: "https://github.com/{{ _pushgateway_repo }}/releases/download/v{{ pushgateway_version }}/sha256sums.txt"

pushgateway_web_listen_address: "0.0.0.0:9091"
pushgateway_web_telemetry_path: "/metrics"

# External address on which pushgateway is available.
# Useful when behind reverse proxy, e.g.: https://example.org/pushgateway
pushgateway_web_external_url: ""

# Optional extra flags to be passed to pushgateway binary, e.g.
# ['--log.level=debug', '--log.format=json', '--web.enable-admin-api']
pushgateway_config_flags_extra: []

pushgateway_tls_server_config: {}

pushgateway_http_server_config: {}

pushgateway_basic_auth_users: {}

pushgateway_binary_install_dir: "/usr/local/bin"
pushgateway_system_group: "pushgateway"
pushgateway_system_user: "{{ pushgateway_system_group }}"
pushgateway_config_dir: "/etc/pushgateway"

# Local path to stash the archive and its extraction
pushgateway_local_cache_path: "/tmp/pushgateway-{{ ansible_facts['system'] | lower }}-{{ _pushgateway_go_ansible_arch }}/{{ pushgateway_version }}"
