---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include the role
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        vault_alertmanager_telegram_bot_token: 1111111111
        vault_alertmanager_telegram_chat_id: -1111111111
        vault_alertmanager_telegram_home_chat_id: -1111111111
