---
_influxdb_exporter_go_ansible_arch: "{{ {'i386': '386',
                                'x86_64': 'amd64',
                                'aarch64': 'arm64',
                                'armv7l': 'armv7',
                                'armv6l': 'armv6'}.get(ansible_facts['architecture'], ansible_facts['architecture']) }}"
_influxdb_exporter_repo: "prometheus/influxdb_exporter"
_influxdb_exporter_github_api_headers: "{{ {'GITHUB_TOKEN': lookup('ansible.builtin.env', 'GITHUB_TOKEN')} if (lookup('ansible.builtin.env', 'GITHUB_TOKEN')) else {} }}"

_influxdb_exporter_binaries: ['influxdb_exporter']
