---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
platforms:
  - name: molecule-instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-/sbin/init}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  config_options:
    defaults:
      display_skipped_hosts: false
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: "../../:../../../:${ANSIBLE_ROLES_PATH}"
scenario:
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - converge
    - verify
    - destroy
verifier:
  name: ansible
