---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        apache_exporter_web_listen_address: "127.0.0.1:9118"
        apache_exporter_tls_server_config:
          cert_file: /etc/apache_exporter/tls.cert
          key_file: /etc/apache_exporter/tls.key
        apache_exporter_http_server_config:
          http2: true
        apache_exporter_basic_auth_users:
          randomuser: examplepassword
        apache_exporter_version: 1.0.8
