---
_mongodb_exporter_go_ansible_arch: "{{ {'i386': '386',
                                    'x86_64': 'amd64',
                                    'aarch64': 'arm64',
                                    'armv7l': 'armv7',
                                    'armv6l': 'armv6'}.get(ansible_facts['architecture'], ansible_facts['architecture']) }}"
_mongodb_exporter_repo: "percona/mongodb_exporter"
_github_api_headers: "{{ {'GITHUB_TOKEN': lookup('ansible.builtin.env', 'GITHUB_TOKEN')} if (lookup('ansible.builtin.env', 'GITHUB_TOKEN')) else {} }}"
_mongodb_exporter_binaries: ['mongodb_exporter']
