---
- name: Common preflight
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: preflight.yml
  vars:
    _common_web_listen_address: "{{ apache_exporter_web_listen_address }}"

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        apache_exporter_web_listen_address is string

- name: Assert that TLS config is correct
  when: apache_exporter_tls_server_config | length > 0
  block:
    - name: Assert that TLS key and cert path are set
      ansible.builtin.assert:
        that:
          - "apache_exporter_tls_server_config.cert_file is defined"
          - "apache_exporter_tls_server_config.key_file is defined"

    - name: Check existence of TLS cert file
      ansible.builtin.stat:
        path: "{{ apache_exporter_tls_server_config.cert_file }}"
      register: __apache_exporter_cert_file

    - name: Check existence of TLS key file
      ansible.builtin.stat:
        path: "{{ apache_exporter_tls_server_config.key_file }}"
      register: __apache_exporter_key_file

    - name: Assert that TLS key and cert are present
      ansible.builtin.assert:
        that:
          - "__apache_exporter_cert_file.stat.exists"
          - "__apache_exporter_key_file.stat.exists"

- name: Discover latest version
  ansible.builtin.set_fact:
    apache_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/{{ _apache_exporter_repo }}/releases/latest', headers=_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: apache_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - apache_exporter_version == "latest"
  tags:
    - apache_exporter
    - install
    - apache_exporter_install
    - download
    - apache_exporter_download
