---
- name: Common preflight
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: preflight.yml
  vars:
    _common_web_listen_address: "{{ consul_exporter_web_listen_address }}"

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        consul_exporter_web_listen_address is string
        or
        consul_exporter_web_listen_address | type_debug == "list"

- name: Assert that TLS config is correct
  when: consul_exporter_tls_server_config | length > 0
  block:
    - name: Assert that TLS key and cert path are set
      ansible.builtin.assert:
        that:
          - "consul_exporter_tls_server_config.cert_file is defined"
          - "consul_exporter_tls_server_config.key_file is defined"

    - name: Check existence of TLS cert file
      ansible.builtin.stat:
        path: "{{ consul_exporter_tls_server_config.cert_file }}"
      register: __consul_exporter_cert_file

    - name: Check existence of TLS key file
      ansible.builtin.stat:
        path: "{{ consul_exporter_tls_server_config.key_file }}"
      register: __consul_exporter_key_file

    - name: Assert that TLS key and cert are present
      ansible.builtin.assert:
        that:
          - "__consul_exporter_cert_file.stat.exists"
          - "__consul_exporter_key_file.stat.exists"

- name: Discover latest version
  ansible.builtin.set_fact:
    consul_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/{{ _consul_exporter_repo }}/releases/latest', headers=_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: consul_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - consul_exporter_version == "latest"
  tags:
    - consul_exporter
    - install
    - consul_exporter_install
    - download
    - consul_exporter_download
