---
_fail2ban_exporter_go_ansible_arch: "{{ {'i386': '386',
  'x86_64': 'amd64',
  'aarch64': 'arm64',
  'armv7l': 'armv7',
  'armv6l': 'armv6'}.get(ansible_facts['architecture'], ansible_facts['architecture']) }}"
_fail2ban_exporter_repo: 24199687
_fail2ban_exporter_binaries: ["fail2ban_exporter"]
