---
_alertmanager_go_ansible_arch: "{{ {'i386': '386',
  'x86_64': 'amd64',
  'aarch64': 'arm64',
  'armv7l': 'armv7',
  'armv6l': 'armv6'}.get(ansible_facts['architecture'], ansible_facts['architecture']) }}"

# The expected location of the amtool configuration file
_alertmanager_amtool_config_dir: "/etc/amtool"
_alertmanager_repo: "prometheus/alertmanager"
_github_api_headers: "{{ {'GITHUB_TOKEN': lookup('ansible.builtin.env', 'GITHUB_TOKEN')} if (lookup('ansible.builtin.env', 'GITHUB_TOKEN')) else {} }}"
_alertmanager_binaries:
  - alertmanager
  - amtool
