name: CI
on:
  workflow_dispatch:
    inputs:
      runTrivy:
        description: Run Trivy scan
        type: boolean
        default: false
        required: false
      runLint:
        description: Run Ansible Lint
        type: boolean
        default: true
        required: false
      runMolecule:
        description: Run Ansible Molecule
        type: boolean
        default: true
        required: false
  push:
    paths-ignore: ["**.md", "LICENSE", ".github/dependabot.yml"]
    branches: ["master", "main"]

env:
  ROLES_PATH: "roles/"

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: CI
  cancel-in-progress: false

jobs:
  init:
    name: Initialize CI for ${{ github.ref_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get roles list in json
        id: roles-list
        run: echo "roles-list=$(ls ${{ env.ROLES_PATH }} | grep -v '^_common$' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        shell: bash

    outputs:
      roles-list: ${{ steps.roles-list.outputs.roles-list }}

  scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [init]
    if: |
      inputs.runTrivy == true ||
      github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scanners: vuln,secret,misconfig
          scan-ref: ./
          format: sarif
          output: results.sarif
          severity: HIGH,CRITICAL
          exit-code: 1
        continue-on-error: true

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif

  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [init]
    if: |
      inputs.runLint == true ||
      github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: true
      matrix:
        roles: ${{ fromJson(needs.init.outputs.roles-list) }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Ansible Lint
        uses: unleftie/ansible-lint-action@v1
        with:
          path: "roles/${{ matrix.roles }}"

  molecule:
    name: Ansible Molecule
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [init]
    if: |
      inputs.runMolecule == true ||
      github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: true
      matrix:
        roles: ${{ fromJson(needs.init.outputs.roles-list) }}
        distro:
          - debian12

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Ansible Molecule
        uses: unleftie/ansible-molecule-action@v1
        with:
          github_token: ${{ github.token }}
          role_name: ${{ matrix.roles }}
          distro: ${{ matrix.distro }}
          working_directory: "roles/${{ matrix.roles }}"

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [init]
    if: github.event_name == 'push'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          semantic_version: 25
          extra_plugins: |
            conventional-changelog-conventionalcommits@9.3.0
            @semantic-release/github@12.0.6
